function el<T extends HTMLElement>(id: string): T {
  return document.getElementById(id) as T;
}

export const ui = {
  p1Container: el('phase1-container'),
  p2Container: el('phase2-container'),
  goalsContainer: el('goals-container'),

  tabJobSearch: el<HTMLButtonElement>('tab-job-search'),
  tabGoals: el<HTMLButtonElement>('tab-goals'),
  tabMacrofirm: el<HTMLButtonElement>('tab-macrofirm'),

  goalGetJob: el('goal-get-job'),
  goalCheckJob: el('goal-check-job'),

  totalReadRow: el('total-read-row'),
  totalReadDisplay: el('total-read-display'),
  availJobs: el('avail-jobs-display'),
  btnBeg: el<HTMLButtonElement>('btn-beg'),
  btnFind: el<HTMLButtonElement>('btn-find'),
  btnApply: el<HTMLButtonElement>('btn-apply'),
  btnInterview: el<HTMLButtonElement>('btn-interview'),
  jobCard: el('job-card'),

  inlineAppRow: el('inline-app-row'),
  unreadAppsDisplay: el('unread-apps-display'),
  appsThruScreeningDisplay: el('apps-thru-screening-display'),
  keywordsSection: el('keywords-section'),
  keywordsDisplay: el('keywords-display'),
  btnKeywordsDown: el<HTMLButtonElement>('btn-keywords-down'),
  btnKeywordsUp: el<HTMLButtonElement>('btn-keywords-up'),
  qualityRow: el('quality-row'),
  rejectedAppsRow: el('rejected-apps-row'),
  rejectedAppsDisplay: el('rejected-apps-display'),
  screeningRateRow: el('screening-rate-row'),
  screeningRateDisplay: el('screening-rate-display'),
  upgradePrettifyT1Row: el('upgrade-prettify-t1-row'),
  upgradePrettifyT2Row: el('upgrade-prettify-t2-row'),
  upgradePrettifyT3Row: el('upgrade-prettify-t3-row'),
  upgradePrettifyT4Row: el('upgrade-prettify-t4-row'),
  btnUpgradePrettifyT1: el<HTMLButtonElement>('btn-upgrade-prettify-t1'),
  btnUpgradePrettifyT2: el<HTMLButtonElement>('btn-upgrade-prettify-t2'),
  btnUpgradePrettifyT3: el<HTMLButtonElement>('btn-upgrade-prettify-t3'),
  btnUpgradePrettifyT4: el<HTMLButtonElement>('btn-upgrade-prettify-t4'),

  upgradeJobSearchT1Row: el('upgrade-job-search-t1-row'),
  upgradeJobSearchT2Row: el('upgrade-job-search-t2-row'),
  upgradeJobSearchT3Row: el('upgrade-job-search-t3-row'),
  btnUpgradeJobSearchT1: el<HTMLButtonElement>('btn-upgrade-job-search-t1'),
  btnUpgradeJobSearchT2: el<HTMLButtonElement>('btn-upgrade-job-search-t2'),
  btnUpgradeJobSearchT3: el<HTMLButtonElement>('btn-upgrade-job-search-t3'),

  automationCardP1: el('automation-p1-card'),
  submitterBadge: el('submitter-level-badge'),
  btnUpgradeSubmitter: el<HTMLButtonElement>('btn-upgrade-submitter'),
  submitterCostDisplay: el('submitter-cost-display'),
  upgradeEfficiencyT1Row: el('upgrade-efficiency-t1-row'),
  upgradeEfficiencyT2Row: el('upgrade-efficiency-t2-row'),
  upgradeEfficiencyT3Row: el('upgrade-efficiency-t3-row'),
  btnUpgradeEfficiencyT1: el<HTMLButtonElement>('btn-upgrade-efficiency-t1'),
  btnUpgradeEfficiencyT2: el<HTMLButtonElement>('btn-upgrade-efficiency-t2'),
  btnUpgradeEfficiencyT3: el<HTMLButtonElement>('btn-upgrade-efficiency-t3'),

  providerContainer: el('provider-container'),
  btnFinite: el<HTMLButtonElement>('provider-finite'),
  btnWeeklink: el<HTMLButtonElement>('provider-weeklink'),
  btnBliply: el<HTMLButtonElement>('provider-bliply'),
  rateFinite: el('rate-finite'),
  rateWeeklink: el('rate-weeklink'),
  rateBliply: el('rate-bliply'),

  parentalUpgradesContainer: el('parental-upgrades-container'),
  upgradeParentT2: el('upgrade-parental-t2'),
  upgradeParentT3: el('upgrade-parental-t3'),
  upgradeParentT4: el('upgrade-parental-t4'),
  btnUpgradeParentT2: el<HTMLButtonElement>('btn-upgrade-parent-t2'),
  btnUpgradeParentT3: el<HTMLButtonElement>('btn-upgrade-parent-t3'),
  btnUpgradeParentT4: el<HTMLButtonElement>('btn-upgrade-parent-t4'),

  level: el('level-display'),
  perf: el('perf-display'),
  appr: el('appr-display'),
  paper: el('paper-display'),
  paperCostDisplay: el('paper-cost-display'),
  reports: el('reports-display'),
  reportRate: el('report-rate-display'),
  timer: el('timer-display'),
  btnPaper: el<HTMLButtonElement>('btn-paper'),
  btnWrite: el<HTMLButtonElement>('btn-write'),
  btnSubmit: el<HTMLButtonElement>('btn-submit'),
  btnCompliment: el<HTMLButtonElement>('btn-compliment'),
  btnLunch: el<HTMLButtonElement>('btn-lunch'),

  typistBadge: el('typist-level-badge'),
  typistCostDisplay: el('typist-cost-display'),
  btnUpgradeTypist: el<HTMLButtonElement>('btn-upgrade-typist'),
  courierBadge: el('courier-level-badge'),
  courierCostDisplay: el('courier-cost-display'),
  btnUpgradeCourier: el<HTMLButtonElement>('btn-upgrade-courier'),
  btnUpgradeProcurement: el<HTMLButtonElement>('btn-upgrade-procurement'),
  procurementStatusDisplay: el('procurement-status-display'),

  money: el('money-display'),
  income: el('income-display'),
  headerFees: el('header-fees'),
  log: el('log'),
  debugPanel: el('debug-panel'),
  bankruptcyOverlay: el('bankruptcy-overlay'),

  dbFiniteMult: el('db-finite-mult'),
  dbWeeklinkMult: el('db-weeklink-mult'),
  dbBliplyMult: el('db-bliply-mult'),
};
