function el<T extends HTMLElement>(id: string): T {
  return document.getElementById(id) as T;
}

export const ui = {
  p1Container: el('phase1-container'),
  p2Container: el('phase2-container'),
  goalsContainer: el('goals-container'),
  emailContainer: el('email-container'),
  emailListView: el('email-list-view'),
  emailDetailView: el('email-detail-view'),
  emailList: el('email-list'),
  emailDetailFrom: el('email-detail-from'),
  emailDetailSubject: el('email-detail-subject'),
  emailDetailBody: el('email-detail-body'),
  emailDetailActions: el('email-detail-actions'),
  btnEmailBack: el<HTMLButtonElement>('btn-email-back'),

  tabJobSearch: el<HTMLButtonElement>('tab-job-search'),
  tabGoals: el<HTMLButtonElement>('tab-goals'),
  tabMacrofirm: el<HTMLButtonElement>('tab-macrofirm'),
  tabEmail: el<HTMLButtonElement>('tab-email'),

  goalGetJob: el('goal-get-job'),
  goalCheckJob: el('goal-check-job'),

  totalReadRow: el('total-read-row'),
  totalReadDisplay: el('total-read-display'),
  availJobs: el('avail-jobs-display'),
  btnBeg: el<HTMLButtonElement>('btn-beg'),
  btnFind: el<HTMLButtonElement>('btn-find'),
  btnApply: el<HTMLButtonElement>('btn-apply'),
  btnInterview: el<HTMLButtonElement>('btn-interview'),
  jobCard: el('job-card'),

  inlineAppRow: el('inline-app-row'),
  applyCreditsRow: el('apply-credits-row'),
  applyCreditsDisplay: el('apply-credits-display'),

  upgradeJobSearchT1Row: el('upgrade-job-search-t1-row'),
  upgradeJobSearchT2Row: el('upgrade-job-search-t2-row'),
  upgradeJobSearchT3Row: el('upgrade-job-search-t3-row'),
  btnUpgradeJobSearchT1: el<HTMLButtonElement>('btn-upgrade-job-search-t1'),
  btnUpgradeJobSearchT2: el<HTMLButtonElement>('btn-upgrade-job-search-t2'),
  btnUpgradeJobSearchT3: el<HTMLButtonElement>('btn-upgrade-job-search-t3'),

  upgradeSubmitterRow: el('upgrade-submitter-row'),
  submitterBadge: el('submitter-level-badge'),
  btnUpgradeSubmitter: el<HTMLButtonElement>('btn-upgrade-submitter'),
  submitterCostDisplay: el('submitter-cost-display'),

  actionsSection: el('actions-section'),
  actionWifiRow: el('action-wifi-row'),
  actionEthernetRow: el('action-ethernet-row'),
  actionGigabitRow: el('action-gigabit-row'),
  btnActionWifi: el<HTMLButtonElement>('btn-action-wifi'),
  btnActionEthernet: el<HTMLButtonElement>('btn-action-ethernet'),
  btnActionGigabit: el<HTMLButtonElement>('btn-action-gigabit'),

  providerContainer: el('provider-container'),
  btnFinite: el<HTMLButtonElement>('provider-finite'),
  btnWeeklink: el<HTMLButtonElement>('provider-weeklink'),
  btnBliply: el<HTMLButtonElement>('provider-bliply'),

  level: el('level-display'),
  perf: el('perf-display'),
  appr: el('appr-display'),
  paper: el('paper-display'),
  paperCostDisplay: el('paper-cost-display'),
  reports: el('reports-display'),
  reportRate: el('report-rate-display'),
  timer: el('timer-display'),
  btnPaper: el<HTMLButtonElement>('btn-paper'),
  btnWrite: el<HTMLButtonElement>('btn-write'),
  btnSubmit: el<HTMLButtonElement>('btn-submit'),
  btnCompliment: el<HTMLButtonElement>('btn-compliment'),
  btnLunch: el<HTMLButtonElement>('btn-lunch'),

  typistBadge: el('typist-level-badge'),
  typistCostDisplay: el('typist-cost-display'),
  btnUpgradeTypist: el<HTMLButtonElement>('btn-upgrade-typist'),
  courierBadge: el('courier-level-badge'),
  courierCostDisplay: el('courier-cost-display'),
  btnUpgradeCourier: el<HTMLButtonElement>('btn-upgrade-courier'),
  btnUpgradeProcurement: el<HTMLButtonElement>('btn-upgrade-procurement'),
  procurementStatusDisplay: el('procurement-status-display'),

  money: el('money-display'),
  income: el('income-display'),
  headerFees: el('header-fees'),
  log: el('log'),
  debugPanel: el('debug-panel'),
  bankruptcyOverlay: el('bankruptcy-overlay'),

  dbFiniteMult: el('db-finite-mult'),
  dbWeeklinkMult: el('db-weeklink-mult'),
  dbBliplyMult: el('db-bliply-mult'),
};
